version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./src/main/resources/init-db.sql:/docker-entrypoint-initdb.d/init.sql
